import random
import time
from turtle import *
screen = Screen()
screen.title("Welcom, watch the race!")
reset()
bgcolor("black")
color('white')
turtle1 = Turtle()
turtle1.color("green", "red")
turtle1.shape("turtle")
turtle1.pu()
turtle1.sety(-10)
turtle1.setx(-100)
turtle2 = Turtle()
turtle2.color("pink", "blue")
turtle2.shape("turtle")
turtle2.pu()
turtle2.sety(10)
turtle2.setx(-100)
setx(100)
setx(-100)
pu()
sety(20)
pd()
setx(100)
setx(-100)
pu()
sety(10)
sety(-20)
pd()
setx(100)
setx(-100)
pu()
setx(0)
sety(10)
ht()
color("gold")
while (turtle1.xcor() < 100 and turtle2.xcor() < 100):
    turtle2.fd(random.randint(15,25))
    turtle1.fd(random.randint(15,25))
    time.sleep(1)
if turtle1.xcor() > turtle2.xcor():
    shape('triangle')
    goto(turtle1.pos())
    st()
    screen.title("Red turtle wins!")
elif turtle2.xcor() > turtle1.xcor():
    shape("triangle")
    goto(turtle2.pos())
    st()
    screen.title("Blue turtle wins!")
    
    
