import turtle
turtle.begin_fill()
turtle.fillcolor("black")
turtle.fd(100)
turtle.rt(90)
turtle.fd(20)
turtle.rt(90)
turtle.fd(100)
turtle.rt(90)
turtle.fd(20)
turtle.rt(90)
turtle.fillcolor("black")
turtle.begin_fill()
turtle.end_fill()
